### PR TITLE
Add installation instructions for suggested packages

### PR DESCRIPTION
**Pull request by pkq**
I thought these might be useful, given how little slidex can do without them. 😉

### CODE REVIEW

**Comment by datalorax** [comment]
Beautiful! Before I merge this, would you mind also adding in {tibble} as a suggests? I keep meaning to add that but forgetting. `tibble::tribble` is used when reproducing tables.

**Comment by pkq** [comment]
Will do! Hold on a sec.

**Comment by pkq** [comment]
Actually, I think that'd fit better with #12. I'll do that there?

**Comment by pkq** [comment]
Wait, I see what you mean. Yeah, here makes sense.

**Comment by datalorax** [comment]
Thanks so much!

**Pull request merged**
